pipeline:
  name: "test_pipeline"
  version: "1"
  
  training:
    algorithm: "RandomForest"
    parameters:
      - key: "n_estimators"
        value: "100"

  dependencies:
    - name: "numpy"
      version: "1.21.0"
    - name: "pandas"
      version: "1.3.3"
    - name: "scikit-learn"
      version: "0.24.2"

  dataprocessing:
    inputPath: "/data/input"
    outputPath: "/data/output"

  deployment:
    targetPlatform: "Docker"
    scalability: 2
